### ISSUE TITLE
Hello, i would like to ask a question about the status of your repository

### ISSUE THREAD

**Issue by MadRatSRP** [wchargin/JGame#8]
Are this project https://sourceforge.net/projects/jgame-engine/ and your repository share the same project? If yes, which is the latest?

**Comment by wchargin** [comment]
Hi @MadRatSRP! No, <https://sourceforge.net/projects/jgame-engine/> is
unrelated to this project. This project is not maintained; it’s just a
small library that I wrote for myself and my classmates when I was in
high school years ago. If you’re looking for a game engine to use for
anything remotely serious, I wouldn’t suggest this project—but if all
you need is a toy, it might still  work. :-)
